### ISSUE TITLE
Option to list all violating rows instead of using e.g.

### ISSUE THREAD

**Issue by mdlincoln** [ropenscilabs/assertr#33]
Excellent package!

I'm wondering if there currently exists (or if their might be in the future) an option in `assert()` that could list each violation of a predicate in the given column, rather than simply listing the number times and one example?

**Comment by tonyfischetti** [comment]
Thanks for the kind words about the package!

Great question! The relative inflexibility of the error reporting mechanism is something that I'm currently working on. In addition to capturing *all* the errors in a data structure of principled design (that could optionally print as a short summary like the one that exists now) it will also optionally allow for *all* the assertr assertions to run and concatenate the errors from each assertion. Is there something more specific that you'd like to see?

**Comment by mdlincoln** [comment]
One neat functionality I've seen is how Hadley handles parsing problems in
readr, attaching a dataframe of all the problems as an attribute of the
actual data frame.

Of course, I'm not sure how well that would play with a pipe-able command
like assert ()...

-----
Matthew D. Lincoln, PhD
Department of Art History & Archaeology
University of Maryland
College Park, MD 20742

mlincol1@umd.edu
matthewlincoln.net

**Comment by tonyfischetti** [comment]
As of commit 2b638015c (v2) this is not very much doable. Specifying `error_report` for each verb's `error_fun` parameter will tell you all the violations.
Thanks for the idea and feedback! Let me know if you have any questions! :)
