### ISSUE TITLE
put NEWS bits in releases please

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/assertr#35]
hey @tonyfischetti  - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

* you already keep a `NEWS` file, thanks! but looks like it doesn't include news for your latest CRAN version?
* thanks for git tagging! but can you do a git tag for each CRAN release?
* You have for some releases, but could you please use the [releases tab](https://github.com/ropensci/RStars/releases) on this repo to include the associated NEWS items for __every__ tag/version ? thanks 😄

**Comment by tonyfischetti** [comment]
Sure, no problem.
I didn't update the `NEWS` file because it was just a couple of very small changes so that the newest `dplyr` didn't break it
