### ISSUE TITLE
num_row_NAs doesn't work when "data.frame" is not in the first position of class(my_data)

### ISSUE THREAD

**Issue by malexan** [ropenscilabs/assertr#37]
When `num_row_NAs` gets an object when "data.frame" class is not the first one (e.g. output from dplyr/tibble) it throws an error __"data" must be a data.frame (or matrix)__.

```r
mtcars <- tibble::as_tibble(mtcars)
[1] "tbl_df"     "tbl"        "data.frame"
assertr::num_row_NAs(mtcars)
Error: "data" must be a data.frame (or matrix)
```

It is due to a line in [row-redux.R](https://github.com/ropenscilabs/assertr/blob/f521de2c9b04805d9375eaa0ad50bc03676ce65c/R/row-redux.R):

```r
if(!(class(data) %in% c("matrix", "data.frame")))
```

It can be fixed, e.g., as follows:

```r
if(!(any(class(data) %in% c("matrix", "data.frame"))))
```

**Comment by tonyfischetti** [comment]
Thanks a lot, @malexan! It's a very simple fix as you pointed out. Before I make this change, I wanted to give you the option of submitting the pull request yourself—you know... to get credit for the contribution :)
If not, I can change it no problem

**Comment by malexan** [comment]
Hi @tonyfischetti, thank you for the offer :)

**Comment by tonyfischetti** [comment]
No problem! Thanks for the pull request!
