### ISSUE TITLE
Feature request: Add return_true option to verify

### ISSUE THREAD

**Issue by dpprdan** [ropenscilabs/assertr#38]
Would it be possible to add a `return_true` option to `verify` and `assert` that returns just a short "TRUE" if the `expr` or `predicate` is `TRUE` instead of returning the data?

**Comment by tonyfischetti** [comment]
So, currently, the data is returned so that multiple assertions can be changed. Are you suggesting that a parameter like `return_true` be added so that the user can optionally specify it in the parameter list for use with if statements, etc... instead of for chaining? If so, I like that idea.

**Comment by dapper2dan** [comment]
I think I do. I'm not completely sure whether I understand you correctly now, so just a short example from the help file:
`mtcars %>%
    verify(nrow(mtcars) > 2)`
returns the data
`mtcars %>%
    verify(nrow(mtcars) > 2, return_true = TRUE)`
returns just 
`[1] TRUE`

I guess the option could also be named `return` with `data` (default) and `logical` as possible values. Not sure, what would be better.

**Comment by tonyfischetti** [comment]
I think this is a great idea. I'll update this issue when this is implemented! Thank you!

**Comment by dapper2dan** [comment]
Great, thanks! 
Needless to say that this also applies to `insist` and the `_rows` commands...

**Comment by tonyfischetti** [comment]
Of course.
Also--and my apologies if you've already realized this--you can get an checking function to return `FALSE` instead of an error like so...
```
mtcars %>% assert(within_bounds(1, 7), cyl, error_fun=function(x) return(FALSE))
```
It doesn't solve the problem of controlling the return value when it's `TRUE` but I just thought I'd mention it.
I'm working on this issue today

**Comment by dapper2dan** [comment]
No, I did not know, but I actually like that R stops if there is an error.

**Comment by tonyfischetti** [comment]
If you want to test this out, clone the dev branch and install it. `help("assert"` under "details" explains how to do this. (`....success_fun=success_logical`)

**Comment by tonyfischetti** [comment]
As of commit 2b638015c, all verbs have a `success_fun` and `error_fun` parameter. The behavior you're looking for can be achieved by specifying `success_logical` and `error_logical` for those parameters, respectively. 
Thanks for the idea and feedback! Let me know if you have any questions! :)
